version: "2"

services:
  postgres:
    image: postgres:14.5
    restart: always
    container_name: rssmarkable-db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.development.local

volumes:
  postgres:
