databases:
  - name: db
    databaseName: db

services:
  - type: web
    name: app
    env: docker
    region: frankfurt
    dockerfilePath: ./provision/prod/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: API_KEY
        sync: false
