# fly.toml app configuration file generated for syncreads on 2023-05-31T19:16:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "syncreads"
primary_region = "lax"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.connectivity]
    grace_period = "15s"
    interval = "10s"
    timeout = "7s"
    type = "http"
    method = "GET"
    path = "/api/health"
    [checks.connectivity.headers]
      Content-Type = "application/json"