project_id = "rssmarkable"

[api]
port = 54321
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
port = 54323
api_url = "http://localhost"

[realtime]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = false

[analytics]
enabled = false
