# fly.toml app configuration file generated for rssmarkable on 2023-05-31T19:16:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rssmarkable"
primary_region = "waw"

[build]
  dockerfile = "./provision/prod/Dockerfile"

[build.args]
  NEXT_PUBLIC_WS_URL="wss://rssmarkable.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
