version: "2"

name: rssmarkable
services:
  postgres:
    image: postgres:14.5
    restart: always
    container_name: db
    hostname: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ../../.env.development.local

  redis:
    image: bitnami/redis:7.0
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/bitnami/redis/data
    env_file:
      - ../../.env.development.local

  # TODO: In the future NextJS app also should be dockerized on dev environment, but now hot reload is not supported in container
  # app:
  #   build:
  #     context: ../..
  #     dockerfile: provision/dev/Dockerfile
  #     target: starter
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ../..:/app
  #   env_file:
  #     - ../../.env.development.local

volumes:
  postgres:
  redis:
  # app:
