name: Deployment

on:
  push:
    # branches: [main]
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  # deploy:
  #   name: 🚀 Deploy
  #   runs-on: ubuntu-latest
  #   environment: Production
  #   steps:
  #     - name: ✅ Checkout code
  #       uses: actions/checkout@v3

  #     - name: 🔨 Setup Fly
  #       uses: superfly/flyctl-actions/setup-flyctl@master

  #     - name: 💨 Fly!
  #       run: flyctl deploy --remote-only --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
