name: Deployment

on:
  push:
    # branches: [main]
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup
      - name: Build
        run: pnpm build

  # deploy:
  #   name: 🚀 Deploy
  #   runs-on: ubuntu-latest
  #   environment: Production
  #   steps:
  #     - name: ✅ Checkout code
  #       uses: actions/checkout@v3

  #     - name: 🔨 Setup Fly
  #       uses: superfly/flyctl-actions/setup-flyctl@master

  #     - name: 💨 Fly!
  #       run: flyctl deploy --remote-only --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
