name: Deployment

on:
  push:
    # branches: [main]
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v4

      - name: 🎬 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 🔨 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: 🔌 Install
        run: pnpm install

  deploy:
    needs: common
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: pnpm build

  # deploy:
  #   name: 🚀 Deploy
  #   runs-on: ubuntu-latest
  #   environment: Production
  #   steps:
  #     - name: ✅ Checkout code
  #       uses: actions/checkout@v3

  #     - name: 🔨 Setup Fly
  #       uses: superfly/flyctl-actions/setup-flyctl@master

  #     - name: 💨 Fly!
  #       run: flyctl deploy --remote-only --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
