name: Fetch feeds on 6:00 AM every day
on:
  schedule:
    - cron: "*/3 * * * *"
jobs:
  sync:
    name: Fetch feed articles and save to reMarkable cloud.
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: "curl https://rssmarkable.fly.dev/api/sync -H 'api-key: ${{ secrets.API_KEY }}'"
