name: Fetch feeds every 6 hours
on:
  schedule:
    - cron: "* */6 * * *"
jobs:
  sync:
    name: Fetch feed articles and save to reMarkable cloud.
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: "curl https://rssmarkable.onrender.com/api/sync -H 'api-key: ${{ secrets.API_KEY }}'"
