name: Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v3

      - name: 🔨 Setup
        uses: ./.github/workflows/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🖌️ Format
        run: pnpm run format:check

      - name: 📦 Build
        # builds only sync app, because we're building web in Next.js bundle analysis
        run: pnpm run build:sync

      - name: 🛻 Lint
        run: pnpm run lint

      - name: 🧪 Test
        run: pnpm run test:ci
